
version: '3.4'

services:
  datastoreclient:
    image: datastoreclient
    build:
      context: .
      dockerfile: DataStore.Client/Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  datastoreserver:
    image: datastoreserver
    build:
      context: .
      dockerfile: DataStore.Server/Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
